### ISSUE TITLE
Button focus state issue - a11y

### ISSUE THREAD

**Issue by melodyma** [veteransaffairscanada/vac-benefits-directory#738]
The pulsing focus states for buttons can make someone feel nauseous/trigger motion sickness, especially for the clientele you're servicing. I would suggest to stick with simple focus states.

**Comment by maxneuvians** [comment]
Fixed in #754

**Comment by melodyma** [comment]
Hi @maxneuvians - Thanks for fixing the ripple animation for focus on mouse so quickly! However, it's not fixed for keyboard tab. Opened new issue #796
